// Build or verify manifest.json.
//
//   node tools/manifest.mjs            rewrite manifest.json from what is on disk
//   node tools/manifest.mjs --verify   fail if any hash disagrees with disk
//
// ⛔ The hash covers text.md ONLY — the words someone actually accepted. notes.md is our
// reasoning and may be revised; the accepted text may not. That distinction is the whole
// evidentiary point: a capture record stores this hash, so it proves WHICH BYTES were shown,
// not merely which version string was current.
//
// Private-record hashes are entered by hand from the shared drive (see README). Nothing on
// G:\ is read by this script, and nothing privileged belongs in this repo.

import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1");
const LIC = join(ROOT, "licences");
const OUT = join(ROOT, "manifest.json");

const sha256 = (p) => createHash("sha256").update(readFileSync(p)).digest("hex");
const dirs = (p) => readdirSync(p, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => d.name);

const licences = [];
for (const product of dirs(LIC)) {
  for (const kind of dirs(join(LIC, product))) {
    for (const version of dirs(join(LIC, product, kind))) {
      const dir = join(LIC, product, kind, version);
      const text = join(dir, "text.md");
      if (!existsSync(text)) continue;
      licences.push({
        id: `${product}/${kind}`,
        product,
        kind,
        version,
        text: relative(ROOT, text).split(String.fromCharCode(92)).join("/"),
        sha256: sha256(text),
        bytes: readFileSync(text).length,
      });
    }
  }
}
licences.sort((a, b) => a.id.localeCompare(b.id) || a.version.localeCompare(b.version));

// Preserve hand-maintained sections across a rebuild.
const prev = existsSync(OUT) ? JSON.parse(readFileSync(OUT, "utf8")) : {};
const manifest = {
  $comment:
    "Generated by tools/manifest.mjs. sha256 covers text.md only. Published versions are IMMUTABLE — never edit a text.md that anyone has accepted; add a new version directory instead.",
  generated: prev.generated ?? null,
  licences,
  private_record: prev.private_record ?? {
    $comment:
      "SHA-256 of documents held on G:\\Shared drives\\Wezdenko L.L.C\\Legal\\. Hashes only — never the documents. Publishing a hash proves a document existed and has not changed WITHOUT disclosing it or waiving privilege.",
    documents: [],
  },
};

if (process.argv.includes("--verify")) {
  const on_disk = JSON.stringify(licences);
  const recorded = JSON.stringify((prev.licences ?? []).map(({ id, product, kind, version, text, sha256, bytes }) => ({ id, product, kind, version, text, sha256, bytes })));
  if (on_disk !== recorded) {
    console.error("MANIFEST DRIFT — manifest.json does not match the files on disk.");
    console.error("If a text.md changed, that text was already published. Add a NEW version instead.");
    process.exit(1);
  }
  console.log(`manifest OK — ${licences.length} licence texts verified`);
} else {
  manifest.generated = new Date().toISOString();
  writeFileSync(OUT, JSON.stringify(manifest, null, 2) + "\n");
  console.log(`manifest written — ${licences.length} licence texts`);
  for (const l of licences) console.log(`  ${l.id}@${l.version}  ${l.sha256.slice(0, 16)}…  ${l.bytes}b`);
}
